name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: RamspheldOnyangoOchieng
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_timezone: Africa/Nairobi
          
          # Output file name
          filename: github-metrics.svg
          
          # Lines of code (Shows impact)
          plugin_lines: yes
          
          # Increased limits for active users
          plugin_activity_load: 1000
          plugin_activity_days: 0
          
          # Achievements
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_limit: 8
          plugin_achievements_display: compact
          
          # Habits
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_charts: yes
          
          # Languages
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          
          # Calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
